type: mermaid
include_services:
  - v1-service
  - v2-service
exclude_grpc_services:
  - /foo.bar.v0.Service
grpc_serivce_alias:
  /foo.bar.v1.Service: v1-service
  /foo.bar.v2.Service: v2-service
  /foo.bar.v3.Service: v3-service
is_skip_self_call: true
no_response: true
